# Generated by Django 3.2.7 on 2022-04-07 11:36

from django.db import migrations, models
import todo.models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='group_id',
            field=models.CharField(blank=True, default=todo.models.group_id_creator, editable=False, max_length=20, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='group',
            name='link',
            field=models.CharField(blank=True, default=todo.models.group_link_creator, editable=False, max_length=30, unique=True),
        ),
    ]
