# Generated by Django 3.2.7 on 2022-04-07 06:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import todo.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('todo', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='Group',
            fields=[
                ('group_id', models.CharField(blank=True, default=todo.models.group_id_creator, editable=False, max_length=10, primary_key=True, serialize=False, unique=True)),
                ('link', models.CharField(blank=True, default=todo.models.group_link_creator, editable=False, max_length=19, unique=True)),
                ('name', models.CharField(max_length=50)),
                ('members', models.ManyToManyField(related_name='group_members', to=settings.AUTH_USER_MODEL)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
