# Generated by Django 3.2.7 on 2022-04-08 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0002_alter_task_finished_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='group',
        ),
        migrations.AddField(
            model_name='task',
            name='group',
            field=models.ManyToManyField(to='todo.Group'),
        ),
    ]
