# Generated by Django 3.2.7 on 2022-04-08 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0003_auto_20220408_1435'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.CharField(choices=[('C', 'Created'), ('D', 'Doing'), ('F', 'Finished')], max_length=1),
        ),
    ]
