# Generated by Django 3.2.7 on 2022-04-08 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0005_alter_task_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.CharField(choices=[('C', 'Created'), ('D', 'Doing'), ('F', 'Finished')], default='C', max_length=1),
        ),
    ]
