# Generated by Django 3.2.7 on 2022-04-09 09:06

from django.db import migrations, models
import todo.models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0006_alter_task_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='avatar',
            field=models.ImageField(blank=True, upload_to=todo.models.user_avatar),
        ),
    ]
